---
title: "Testat Samira Igwe"
author: "Samira Igwe"
date: "19 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Gesamnetzwerk erstellen, echo=FALSE}

library(igraph) #verwendete library für die Visualisierung des Netzwerks

# Edge und Nodelist werden aus Github eingelesen
edgelist <- read.csv("https://raw.githubusercontent.com/si027/Testat-Samira-Igwe-VfB/main/edgelist%20testat.csv", header=T, as.is=T, sep = ",")
nodelist <- read.csv("https://raw.githubusercontent.com/si027/Testat-Samira-Igwe-VfB/main/nodelist%20testat.csv", header=T, as.is=T, sep = ",")

# Die Matrix wird aus der Edgelist erstellt
edgematrix <-as.matrix(edgelist)

# edge und nodelist zusammenstellen und igraph-Objekt erstellen
Kader <- graph_from_data_frame(d=edgematrix, directed=T)
Kader
```

```{r Einfache Visualisierung des Netzwerkes, fig.height=17, fig.width=30}

plot(Kader,                                     
     asp=0,
     layout=layout_nicely,
     rescale=TRUE,
      edge.color= "black",
    vertex.frame.color="blue",
    vertex.color="pink2",
    edge.color= "black",
    edge.arrow.size= .2,
    vertex.size=degree(Kader)*1,
    main = "VfB Kader Netzwerk",
    sub= "Rückennumer,vorheriger Verein und die Nationalität" ,
)
 #Es können mehrere Layouts für die                                                             Visualisierung verwendet werden bsp.                                                          layout_with_kk ich habe mich jetzt aber für                                                    layout_nicely entschieden, damit wird                                                         automatisch ein passendes Layout gewählt.
# Die Knotengröße wird mit Faktor 4                                                              multipliziert um die Knoten etwas zu entzerren.
# Die Ränderfarbe der Knoten,die Knoten selbst                                                  und die Farbe der Kanten kann beliebig gewählt                                                werden. Die Größe der "Pfeilspitzen" kann auch                                                frei gewählt werden. Mit main habe ich meinem                                                  Netzwerk noch eine Überschrift gegeben und mit                                                 sub eine Unterüberschrift.

```
